FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["WebApplication1/CountriesAPI.API.csproj", "WebApplication1/"]
COPY ["CountriesAPI.Application/CountriesAPI.Application.csproj", "CountriesAPI.Application/"]
COPY ["CountriesAPI.Domain/CountriesAPI.Domain.csproj", "CountriesAPI.Domain/"]
COPY ["CountriesAPI.Infrastructure/CountriesAPI.Infrastructure.csproj", "CountriesAPI.Infrastructure/"]
RUN dotnet restore "WebApplication1/CountriesAPI.API.csproj"
COPY . .
WORKDIR "/src/WebApplication1"
RUN dotnet build "CountriesAPI.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CountriesAPI.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CountriesAPI.API.dll"]